name: flutter_firebase_login
description: Package to handle firebase login
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: ^1.1.0
  flutter_shared_codebase:
    git:
      url: git@github.com:siddhartha-gupta/flutter_shared_codebase.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/twitter.png
